# Generated by Django 4.1.3 on 2022-12-09 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number can be one of these forms: +989XXXXXXXXX | 09XXXXXXXXX', regex='^(\\+989|09)+\\d{9}$')]),
        ),
    ]
