# Generated by Django 4.1.3 on 2022-12-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
