# Generated by Django 4.1.3 on 2022-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('priority',), 'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
