# Generated by Django 4.1.3 on 2022-12-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='property',
            field=models.ManyToManyField(related_name='products', to='product.property'),
        ),
    ]
