# Generated by Django 4.1.3 on 2022-12-11 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_property_product_product_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='property',
            new_name='properties',
        ),
    ]
