# Generated by Django 4.1.3 on 2022-12-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_properties_alter_property_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('is_sub', 'name'), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
