# Generated by Django 4.1.3 on 2022-12-10 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_coupon_created_alter_coupon_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('is_paid', '-updated')},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receipt',
        ),
        migrations.AddField(
            model_name='order',
            name='body',
            field=models.CharField(default='Not specified', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Not specified', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_order', to='orders.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='XXXXXXXXXX', max_length=10, validators=[django.core.validators.RegexValidator('\\d{10}', message='Invalid Postal code')]),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('checking', 'CHECKING'), ('sending', 'SENDING'), ('done', 'DONE')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('no', 'NO'), ('supplying', 'SUPPLYING')], default='OK', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
