# Generated by Django 4.1.3 on 2022-12-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_rename_paid_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='body',
            field=models.CharField(choices=[], default='Not specified', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[], default='Not specified', max_length=20),
        ),
    ]
