# Generated by Django 4.1.3 on 2022-12-11 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_address_created_alter_address_updated_and_more'),
        ('orders', '0004_alter_order_body_alter_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_orders', to='customers.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='body',
            field=models.CharField(default='Not set', editable=False, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Not set', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='0000000000', editable=False, max_length=10, validators=[django.core.validators.RegexValidator('\\d{10}', message='Invalid Postal code')]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
