# Generated by Django 4.1.3 on 2022-12-11 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_address_alter_order_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='body',
            field=models.CharField(default='Not set', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Not set', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\d{10}', message='Invalid Postal code')]),
        ),
    ]
