# Generated by Django 4.1.3 on 2022-12-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_address_alter_order_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='body',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
