# Generated by Django 4.1.4 on 2022-12-29 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_coupon_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='body',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('\\d{10}', message='Invalid Postal code')], verbose_name='Postal Code'),
        ),
    ]
