# Generated by Django 4.1.9 on 2023-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_phone_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_code',
            field=models.CharField(max_length=20, null=True, verbose_name='Transaction Code'),
        ),
    ]
