# Generated by Django 4.1.3 on 2022-12-04 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.user')),
                ('is_customer', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
    ]
