# Generated by Django 4.1.3 on 2022-12-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_address_postal_code_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='body',
            field=models.TextField(max_length=120),
        ),
    ]
